language: c
addons:
  apt:
    packages: &1
    - lcov
# Compiler selection
compiler:
  - clang
  - gcc
script:
# Build steps
  - mkdir -p build && cd build
  - cmake ..
  - make && make test
after_success:
# Creating report
  - mkdir -p build && cd build
  - cmake -DENABLE_COVERAGE=ON ..
  - make
  - make test
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash)
