version: 18.6.{build}
build_script:
- cmd: >-
    cd c:\projects\never

    mkdir build

    cd build

    cmake -G"Visual Studio 14" -DCMAKE_BUILD_TYPE=Debug ..

    cmake --build . --config %CMAKE_BUILD_TYPE%

    ctest --verbose -C "Debug"
