version: 1.0.{build}
install:
    - cd c:\
    # Install Flex / Bison
    - appveyor DownloadFile https://sourceforge.net/projects/winflexbison/files/old_versions/win_flex_bison-2.5.6.zip
    - 7z x win_flex_bison-2.5.6.zip > nul
build_script:
    - cd c:\projects\never
    - mkdir build
    - cd build

    - cmake -G"Visual Studio 14" -DYY_NO_UNISTD_H -DCMAKE_BUILD_TYPE=Debug -DFLEX_EXECUTABLE:FILEPATH=c:/win_flex.exe -DBISON_EXECUTABLE:FILEPATH=c:/win_bison.exe ..
    - cmake --build . --config %CMAKE_BUILD_TYPE%
    - ctest --verbose -C "Debug"
