site_name: never-lang
site_author: Sławomir Maludziński
repo_url: https://github.com/never-lang/never
repo_name: GitHub
theme:
    name: readthedocs
    custom_dir: docs/custom_theme
    highlightjs: false

nav:
   - Documentation: index.md
   - Tutorials:
       - Never on the Web: never-web.md
       - Sorting - Quick Sort: qsort.md
       - Data Structures - Binary Tree: btree.md
       - Dynamic Programming - Rod Cutting : rodcut.md
       - Tribute to Alonso C.: curradd.md
       - Fizz Buzz: fizzbuzz.md
       - Pythagorean Triangle: pitria.md
       - Tail Recursion: tailrec.md
       - Neural Network: perceptron.md
       - Wave: wave.md
       - Brain F***: brainf.md
       - FFI: ffi.md
   - Contact: contact.md

